schema = 3

[mod]
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.3.0"
    hash = "sha256-wfVjNZsGG1WoNC5aL+kdcy6QXPgZo4THAevZ1787md8="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.2"
    hash = "sha256-/W6qGilFlZNTb9Uq48xGZ4IbsVeSwJiAMLw4wiNYHLI="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.22.0"
    hash = "sha256-XiTsDCKK27Wn77deJ6X2ulIjqahXgOxA7t2YCsLltFY="
  [mod."github.com/montanaflynn/stats"]
    version = "v0.7.1"
    hash = "sha256-0QXUA/syOtDSBooh3isAffrVAjpSoBmSMMuZfO5maHg="
  [mod."github.com/uptrace/opentelemetry-go-extra/otelutil"]
    version = "v0.2.3"
    hash = "sha256-fEHqHUvCvJTfNFkh4HioOuLA+eKipCGXW04a0l4iSAM="
  [mod."github.com/uptrace/opentelemetry-go-extra/otelzap"]
    version = "v0.2.3"
    hash = "sha256-Rf3hJRgyVedOhqhayVl1kACWzVhbKHZY1j6pzGeeoh8="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.46.1"
    hash = "sha256-H7GeyxyGcxVRCnR0J7HvpWi3QhwsXGF/IunQMpfkXhw="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.29.0"
    hash = "sha256-r7tAmSEaiM9EMH7+Qo/iwvo4CE4hu3J7yJd2TQPXym4="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.29.0"
    hash = "sha256-LMagVOQJnNko5aAqx+fXpK87fISqEno7igur/SJqboU="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"]
    version = "v1.29.0"
    hash = "sha256-3/5cSVfHsK8pPItAwRVaBHztOpnlRha8bne/cPF3WL4="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.29.0"
    hash = "sha256-8gm1J5gCGW6LilOopNh4UlgsY2QaTjhO4py2sV2CSmw="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.29.0"
    hash = "sha256-zYvsYCrRvY9McWEbjr7rQS90vCgLAKbJcCGeJvMhBUc="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.29.0"
    hash = "sha256-VdqoHwkkEZ3lUbgNHJkTThnvXe2pVfun9dFhZhcnouU="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.3.1"
    hash = "sha256-WaXW64jWowTDlNYDHiGKmHzRUrwJ8Rkymyvz7W6UHd8="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.26.0"
    hash = "sha256-EUQnALSDtoJryWp01K/PMbRUvQYG1uDbqGnlJ/7thE4="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20231110203233-9a3e6036ecaa"
    hash = "sha256-m1T4KePBRCJpAjnuq4BnDYXebOHiVI6h2489XD5R9BA="
  [mod."golang.org/x/net"]
    version = "v0.28.0"
    hash = "sha256-WdH/mgsX/CB+CiYtXEwJAXHN8FgtW2YhFcWwrrHNBLo="
  [mod."golang.org/x/sys"]
    version = "v0.24.0"
    hash = "sha256-P0fsA+qy9taYHWPTtCs5XmrJ1i8tWfvkno+PNuc2elw="
  [mod."golang.org/x/text"]
    version = "v0.17.0"
    hash = "sha256-R8JbsP7KX+KFTHH7SjRnUGCdvtagylVOfngWEnVSqBc="
  [mod."gonum.org/v1/gonum"]
    version = "v0.15.1"
    hash = "sha256-A1KjWeZNRVBENySDQA5WpJBkr8qkPh+kWamUUIMcixE="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20240822170219-fc7c04adadcd"
    hash = "sha256-e9bJpQnQRiQc3EVDhjtD6rDS2mZk38RmRJ13xu9Qt+w="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20240822170219-fc7c04adadcd"
    hash = "sha256-4T4DTrmFbqT4tD7PSL7Ie7u8ZN2iwGkhK02nWugssxk="
  [mod."google.golang.org/grpc"]
    version = "v1.65.0"
    hash = "sha256-YP4dewjs+YuTH7rD1p/AFNoKHlk037wbVvSLVAtewIA="
  [mod."google.golang.org/protobuf"]
    version = "v1.34.2"
    hash = "sha256-nMTlrDEE2dbpWz50eQMPBQXCyQh4IdjrTIccaU0F3m0="
